# Generated by Django 2.1.2 on 2019-05-18 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('genre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_developer', models.ForeignKey(blank=True, null=True, on_delete=None, to='developer.Developer')),
                ('favorite_genre', models.ForeignKey(blank=True, null=True, on_delete=None, to='genre.Genre')),
                ('favorite_tags', models.ManyToManyField(blank=True, to='tag.Tag')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
