# Generated by Django 2.1.2 on 2019-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190514_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998)]),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(blank=True, choices=[(10, '**********'), (9, '*********'), (8, '********'), (7, '*******'), (6, '******'), (5, '*****'), (4, '****'), (3, '***'), (2, '**'), (1, '*')]),
        ),
    ]
