# Generated by Django 2.0.2 on 2018-03-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_recommendation.Developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2000, 2000), (2005, 2005), (2003, 2003), (1997, 1997), (2001, 2001), (1995, 1995), (1990, 1990), (2004, 2004), (1996, 1996), (1991, 1991), (2015, 2015), (1998, 1998), (2018, 2018), (2010, 2010), (2009, 2009), (2014, 2014), (2008, 2008), (2013, 2013), (2011, 2011), (2006, 2006), (1994, 1994), (2012, 2012), (2007, 2007), (1993, 1993), (1992, 1992), (2002, 2002), (2017, 2017)]),
        ),
    ]
