# Generated by Django 2.0.2 on 2018-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_recommendation', '0002_auto_20180325_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=64)),
            ],
        ),
    ]
