# Generated by Django 2.0.4 on 2018-10-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_recommendation', '0003_gamingquotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamingQuotes',
        ),
    ]
